version: '3.4'

services:
  containerizedjango:
    image: containerizedjango
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    container_name: containerized_jango
    command: python manage.py runserver 0.0.0.0:8000
